GMAIL_USERNAME: 'commutecompareteam@gmail.com'
GMAIL_PASSWORD: 'tbrwsyzsfiihulsq'

FB_APP_ID: '559871341148339'
FB_APP_SECRET: '54cafe51b53e7c19aa0153716d93576a' 

GOOGLE_APP_ID: '470942137912-u8snvu8ju9e2nop7s0iu4dq6jvqqg7p2.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'qdhWDJyDzHMGfosbwsnQH02U'
GOOGLE_API_KEY: 'AIzaSyB1TXbgDhq6fHK63-jHt7g5BZFwXSq_f9I'


AMAZON_ACCESS_ID: 'AKIAIPGZT4XDBR2ZLAQQ'
AMAZON_SECRET: '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'
AMAZON_S3_BUCKET_REGION: 'us-east-2'
AMAZON_S3_BUCKET: 'comparecommute'